/* fonts */
export const FontFamily = {
    robotoMedium: "Roboto_medium",
    poppinsSemibold: "Poppins_semibold",
    nunitoBold: "Nunito_bold",
    inriaSansBoldItalic: "Inria Sans_bold_italic",
    inriaSansRegular: "Inria Sans_regular",
    gilroyMediumRegular: "Gilroy-Medium_regular",
    gilroyRegular: "Gilroy_regular",
    nunito: "Nunito",
    barlowSemibold: "Barlow_semibold",
    almaraiBold: "Almarai_bold",
    interSemibold: "Inter_semibold",
    barlowMedium: "Barlow_medium",
    zenDotsRegular: "Zen Dots_regular",
    alegreyaSansRegular: "Alegreya Sans_regular",
    avenirExtrabold: "Avenir_extrabold",
    nunitoRegular: "Nunito_regular",
    avenirRegular: "Avenir_regular",
    odorMeanCheyRegular: "Odor Mean Chey_regular",
    nunitoMedium: "Nunito_medium",
    barlowRegular: "Barlow_regular",
    barlowBold: "Barlow_bold",
    poppinsMedium: "Poppins_medium",
    nunitoSemibold: "Nunito_semibold",
    nunitoExtrabold: "Nunito_extrabold",
    numansRegular: "Numans_regular",
  };
  /* font sizes */
  export const FontSize = {
    size_xs: 8,
    size_sm: 9,
    size_base: 10,
    size_lg: 11,
    size_xl: 12,
    size_2xl: 13,
    size_3xl: 14,
    size_4xl: 15,
    size_5xl: 16,
    size_6xl: 17,
    size_7xl: 18,
    size_8xl: 20,
    size_9xl: 22,
    size_10xl: 24,
    size_11xl: 30,
    size_12xl: 32,
    size_13xl: 34,
  };
  /* Colors */
  export const Color = {
    gray_100: "#fffdfd",
    gray_200: "#9e8989",
    gray_300: "#180202",
    white: "#fff",
    black: "#000",
    dimgray_100: "#6a6969",
    dimgray_200: "#676767",
    dimgray_300: "#7a5858",
    dimgray_400: "#595454",
    dimgray_500: "#4f4f4f",
    mistyrose: "#ebd5d5",
    orangered_100: "#fa4a0c",
    darkgray_100: "#b2b2b2",
    darkgray_200: "#aaa9a9",
    darkgray_300: "#a59393",
    gainsboro: "#d9d9d9",
    rosybrown_100: "#af9696",
    rosybrown_200: "#a98b8b",
    whitesmoke_100: "#f6f6f9",
    whitesmoke_200: "#eee",
    silver_100: "#bdbdbd",
    sienna_100: "#874b4b",
    sienna_200: "#763131",
  };
  /* Margins */
  export const Margin = {
    m_md: 0,
  };
  /* border radiuses */
  export const Border = {
    br_3xs: 3,
    br_2xs: 5,
    br_xs: 10,
    br_sm: 20,
    br_md: 28,
    br_lg: 30,
    br_xl: 40,
    br_2xl: 45,
  };
  